package com.sdu.samus.mapper;

import com.sdu.samus.model.Art;

public interface ArtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int deleteByPrimaryKey(Integer artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insert(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insertSelective(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    Art selectByPrimaryKey(Integer artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKey(Art record);
}