package com.sdu.samus.mapper;

import com.sdu.samus.model.Art;

public interface ArtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(Integer artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insert(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insertSelective(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    Art selectByPrimaryKey(Integer artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(Art record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKey(Art record);

    int deUpdate(String artname);

    int inUpdate(String artname);

    int hasArt(String artname);
}