package com.sdu.samus.mapper;

import com.sdu.samus.model.Cartoon;

public interface CartoonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(Integer cartoonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insert(Cartoon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insertSelective(Cartoon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    Cartoon selectByPrimaryKey(Integer cartoonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(Cartoon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKey(Cartoon record);
}