package com.sdu.samus.mapper;

import com.sdu.samus.model.CityTable;

public interface CityTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int deleteByPrimaryKey(Integer cityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insert(CityTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insertSelective(CityTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    CityTable selectByPrimaryKey(Integer cityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(CityTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citytable
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKey(CityTable record);
}