package com.sdu.samus.mapper;

import com.sdu.samus.model.HobbyInfo;

public interface HobbyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(Integer hobbyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insert(HobbyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insertSelective(HobbyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    HobbyInfo selectByPrimaryKey(Integer hobbyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(HobbyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobbyinfo
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKey(HobbyInfo record);
}