package com.sdu.samus.mapper;

import com.sdu.samus.model.Reading;

public interface ReadingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(Integer readingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insert(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insertSelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    Reading selectByPrimaryKey(Integer readingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKey(Reading record);

    int deUpdate(String readingName);

    int inUpdate(String readingName);

    int hasReading(String readingName);
}