package com.sdu.samus.mapper;

import com.sdu.samus.model.Reading;

public interface ReadingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int deleteByPrimaryKey(Integer readingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insert(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insertSelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    Reading selectByPrimaryKey(Integer readingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKey(Reading record);
}