package com.sdu.samus.mapper;

import com.sdu.samus.model.UserLog;

public interface UserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insertSelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    UserLog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKey(UserLog record);
}