package com.sdu.samus.mapper;

import com.sdu.samus.model.UserRelationship;
import com.sdu.samus.model.UserRelationshipWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface UserRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insert(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int insertSelective(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    UserRelationshipWithBLOBs selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    int updateByPrimaryKey(UserRelationship record);

    int updateDislikeByPrimaryKey(String userid);

    //多参数传递之注解方式示
    int updateLikeByPrimaryKey(@Param("userid") String userid, @Param("hobbyCount") String hobbyCount,@Param("likeList") String likeList);
}