package com.sdu.samus.mapper;

import com.sdu.samus.model.UserRelationship;
import com.sdu.samus.model.UserRelationshipWithBLOBs;
import org.springframework.context.annotation.Bean;

public interface UserRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insert(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int insertSelective(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    UserRelationshipWithBLOBs selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(UserRelationshipWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrelationship
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    int updateByPrimaryKey(UserRelationship record);
}