package com.sdu.samus.model;

public class Art {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art.artId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer artid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art.artName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String artname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art.artCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer artcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art.artId
     *
     * @return the value of art.artId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getArtid() {
        return artid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art.artId
     *
     * @param artid the value for art.artId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setArtid(Integer artid) {
        this.artid = artid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art.artName
     *
     * @return the value of art.artName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getArtname() {
        return artname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art.artName
     *
     * @param artname the value for art.artName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setArtname(String artname) {
        this.artname = artname == null ? null : artname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art.artCount
     *
     * @return the value of art.artCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getArtcount() {
        return artcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art.artCount
     *
     * @param artcount the value for art.artCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setArtcount(Integer artcount) {
        this.artcount = artcount;
    }
}