package com.sdu.samus.model;

public class CityTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citytable.cityId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citytable.cityName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citytable.userCnt
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer usercnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citytable.clusterId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer clusterid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citytable.cityId
     *
     * @return the value of citytable.cityId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citytable.cityId
     *
     * @param cityid the value for citytable.cityId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citytable.cityName
     *
     * @return the value of citytable.cityName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citytable.cityName
     *
     * @param cityname the value for citytable.cityName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citytable.userCnt
     *
     * @return the value of citytable.userCnt
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getUsercnt() {
        return usercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citytable.userCnt
     *
     * @param usercnt the value for citytable.userCnt
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setUsercnt(Integer usercnt) {
        this.usercnt = usercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citytable.clusterId
     *
     * @return the value of citytable.clusterId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getClusterid() {
        return clusterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citytable.clusterId
     *
     * @param clusterid the value for citytable.clusterId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setClusterid(Integer clusterid) {
        this.clusterid = clusterid;
    }
}