package com.sdu.samus.model;

public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.foodId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.foodName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.foodCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer foodcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.foodId
     *
     * @return the value of food.foodId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.foodId
     *
     * @param foodid the value for food.foodId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.foodName
     *
     * @return the value of food.foodName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.foodName
     *
     * @param foodname the value for food.foodName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.foodCount
     *
     * @return the value of food.foodCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getFoodcount() {
        return foodcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.foodCount
     *
     * @param foodcount the value for food.foodCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setFoodcount(Integer foodcount) {
        this.foodcount = foodcount;
    }
}