package com.sdu.samus.model;

public class Game {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gameId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gameName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String gamename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gameCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer gamecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gameId
     *
     * @return the value of game.gameId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gameId
     *
     * @param gameid the value for game.gameId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gameName
     *
     * @return the value of game.gameName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getGamename() {
        return gamename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gameName
     *
     * @param gamename the value for game.gameName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGamename(String gamename) {
        this.gamename = gamename == null ? null : gamename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gameCount
     *
     * @return the value of game.gameCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getGamecount() {
        return gamecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gameCount
     *
     * @param gamecount the value for game.gameCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGamecount(Integer gamecount) {
        this.gamecount = gamecount;
    }
}