package com.sdu.samus.model;

public class HobbyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobbyinfo.hobbyId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer hobbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobbyinfo.hobby
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobbyinfo.count
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobbyinfo.hobbyId
     *
     * @return the value of hobbyinfo.hobbyId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getHobbyid() {
        return hobbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobbyinfo.hobbyId
     *
     * @param hobbyid the value for hobbyinfo.hobbyId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setHobbyid(Integer hobbyid) {
        this.hobbyid = hobbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobbyinfo.hobby
     *
     * @return the value of hobbyinfo.hobby
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobbyinfo.hobby
     *
     * @param hobby the value for hobbyinfo.hobby
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobbyinfo.count
     *
     * @return the value of hobbyinfo.count
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobbyinfo.count
     *
     * @param count the value for hobbyinfo.count
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}