package com.sdu.samus.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer movieid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String moviename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer moviecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieId
     *
     * @return the value of movie.movieId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieId
     *
     * @param movieid the value for movie.movieId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieName
     *
     * @return the value of movie.movieName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieName
     *
     * @param moviename the value for movie.movieName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieCount
     *
     * @return the value of movie.movieCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getMoviecount() {
        return moviecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieCount
     *
     * @param moviecount the value for movie.movieCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setMoviecount(Integer moviecount) {
        this.moviecount = moviecount;
    }
}