package com.sdu.samus.model;

public class Music {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.musicId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer musicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.musicName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String musicname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.musicCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer musiccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.musicId
     *
     * @return the value of music.musicId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getMusicid() {
        return musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.musicId
     *
     * @param musicid the value for music.musicId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setMusicid(Integer musicid) {
        this.musicid = musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.musicName
     *
     * @return the value of music.musicName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getMusicname() {
        return musicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.musicName
     *
     * @param musicname the value for music.musicName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setMusicname(String musicname) {
        this.musicname = musicname == null ? null : musicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.musicCount
     *
     * @return the value of music.musicCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getMusiccount() {
        return musiccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.musicCount
     *
     * @param musiccount the value for music.musicCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setMusiccount(Integer musiccount) {
        this.musiccount = musiccount;
    }
}