package com.sdu.samus.model;

public class Reading {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading.readingId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer readingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading.readingName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String readingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading.readingCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer readingcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading.readingId
     *
     * @return the value of reading.readingId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getReadingid() {
        return readingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading.readingId
     *
     * @param readingid the value for reading.readingId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setReadingid(Integer readingid) {
        this.readingid = readingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading.readingName
     *
     * @return the value of reading.readingName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getReadingname() {
        return readingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading.readingName
     *
     * @param readingname the value for reading.readingName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setReadingname(String readingname) {
        this.readingname = readingname == null ? null : readingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading.readingCount
     *
     * @return the value of reading.readingCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getReadingcount() {
        return readingcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading.readingCount
     *
     * @param readingcount the value for reading.readingCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setReadingcount(Integer readingcount) {
        this.readingcount = readingcount;
    }
}