package com.sdu.samus.model;

public class RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.recordId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer recordid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userId
     *
     * @return the value of record.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userId
     *
     * @param userid the value for record.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.recordId
     *
     * @return the value of record.recordId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.recordId
     *
     * @param recordid the value for record.recordId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }
}