package com.sdu.samus.model;

import java.util.Date;

public class Record extends RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.picture
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.createTime
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.content
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.picture
     *
     * @return the value of record.picture
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.picture
     *
     * @param picture the value for record.picture
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.createTime
     *
     * @return the value of record.createTime
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.createTime
     *
     * @param createtime the value for record.createTime
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.content
     *
     * @return the value of record.content
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.content
     *
     * @param content the value for record.content
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}