package com.sdu.samus.model;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String schoolid5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolId10
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String schoolid10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String schoolname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.eduLevel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String edulevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.leaderDepartment
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String leaderdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.url
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.note
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolId5
     *
     * @return the value of school.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getSchoolid5() {
        return schoolid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolId5
     *
     * @param schoolid5 the value for school.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setSchoolid5(String schoolid5) {
        this.schoolid5 = schoolid5 == null ? null : schoolid5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolId10
     *
     * @return the value of school.schoolId10
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getSchoolid10() {
        return schoolid10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolId10
     *
     * @param schoolid10 the value for school.schoolId10
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setSchoolid10(String schoolid10) {
        this.schoolid10 = schoolid10 == null ? null : schoolid10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolName
     *
     * @return the value of school.schoolName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolName
     *
     * @param schoolname the value for school.schoolName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname == null ? null : schoolname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.eduLevel
     *
     * @return the value of school.eduLevel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getEdulevel() {
        return edulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.eduLevel
     *
     * @param edulevel the value for school.eduLevel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setEdulevel(String edulevel) {
        this.edulevel = edulevel == null ? null : edulevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.city
     *
     * @return the value of school.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.city
     *
     * @param city the value for school.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.leaderDepartment
     *
     * @return the value of school.leaderDepartment
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getLeaderdepartment() {
        return leaderdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.leaderDepartment
     *
     * @param leaderdepartment the value for school.leaderDepartment
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setLeaderdepartment(String leaderdepartment) {
        this.leaderdepartment = leaderdepartment == null ? null : leaderdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.url
     *
     * @return the value of school.url
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.url
     *
     * @param url the value for school.url
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.note
     *
     * @return the value of school.note
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.note
     *
     * @param note the value for school.note
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}