package com.sdu.samus.model;

public class Sport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sportId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer sportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sportName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String sportname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport.sportCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer sportcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sportId
     *
     * @return the value of sport.sportId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getSportid() {
        return sportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sportId
     *
     * @param sportid the value for sport.sportId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setSportid(Integer sportid) {
        this.sportid = sportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sportName
     *
     * @return the value of sport.sportName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getSportname() {
        return sportname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sportName
     *
     * @param sportname the value for sport.sportName
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setSportname(String sportname) {
        this.sportname = sportname == null ? null : sportname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport.sportCount
     *
     * @return the value of sport.sportCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getSportcount() {
        return sportcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport.sportCount
     *
     * @param sportcount the value for sport.sportCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setSportcount(Integer sportcount) {
        this.sportcount = sportcount;
    }
}