package com.sdu.samus.model;

public class Travel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.travelId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer travelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.travelName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String travelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.travelCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer travelcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.travelId
     *
     * @return the value of travel.travelId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getTravelid() {
        return travelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.travelId
     *
     * @param travelid the value for travel.travelId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setTravelid(Integer travelid) {
        this.travelid = travelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.travelName
     *
     * @return the value of travel.travelName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getTravelname() {
        return travelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.travelName
     *
     * @param travelname the value for travel.travelName
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setTravelname(String travelname) {
        this.travelname = travelname == null ? null : travelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.travelCount
     *
     * @return the value of travel.travelCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getTravelcount() {
        return travelcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.travelCount
     *
     * @param travelcount the value for travel.travelCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setTravelcount(Integer travelcount) {
        this.travelcount = travelcount;
    }
}