package com.sdu.samus.model;

public class UserRelationshipWithBLOBs extends UserRelationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.hobbyCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String hobbycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.recomendList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String recomendlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.contactList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String contactlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.hobbyCount
     *
     * @return the value of userrelationship.hobbyCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getHobbycount() {
        return hobbycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.hobbyCount
     *
     * @param hobbycount the value for userrelationship.hobbyCount
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setHobbycount(String hobbycount) {
        this.hobbycount = hobbycount == null ? null : hobbycount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.recomendList
     *
     * @return the value of userrelationship.recomendList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getRecomendlist() {
        return recomendlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.recomendList
     *
     * @param recomendlist the value for userrelationship.recomendList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setRecomendlist(String recomendlist) {
        this.recomendlist = recomendlist == null ? null : recomendlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.contactList
     *
     * @return the value of userrelationship.contactList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getContactlist() {
        return contactlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.contactList
     *
     * @param contactlist the value for userrelationship.contactList
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setContactlist(String contactlist) {
        this.contactlist = contactlist == null ? null : contactlist.trim();
    }
}