package com.sdu.samus.model;

import java.util.Date;

public class UserLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.logId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.loginTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Date logintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.logoutTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private Date logouttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.IP
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.device
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    private String device;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.logId
     *
     * @return the value of userlog.logId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.logId
     *
     * @param logid the value for userlog.logId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.userId
     *
     * @return the value of userlog.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.userId
     *
     * @param userid the value for userlog.userId
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.loginTime
     *
     * @return the value of userlog.loginTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.loginTime
     *
     * @param logintime the value for userlog.loginTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.logoutTime
     *
     * @return the value of userlog.logoutTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public Date getLogouttime() {
        return logouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.logoutTime
     *
     * @param logouttime the value for userlog.logoutTime
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setLogouttime(Date logouttime) {
        this.logouttime = logouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.IP
     *
     * @return the value of userlog.IP
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.IP
     *
     * @param ip the value for userlog.IP
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.device
     *
     * @return the value of userlog.device
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.device
     *
     * @param device the value for userlog.device
     *
     * @mbg.generated Mon Apr 23 19:07:20 CST 2018
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }
}