package com.sdu.samus.model;

public class UserRelationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.active
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String featurevector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.likeCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.totalCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Integer totalcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrelationship.groupList
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String grouplist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.userId
     *
     * @return the value of userrelationship.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.userId
     *
     * @param userid the value for userrelationship.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.active
     *
     * @return the value of userrelationship.active
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.active
     *
     * @param active the value for userrelationship.active
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.city
     *
     * @return the value of userrelationship.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.city
     *
     * @param city the value for userrelationship.city
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.featureVector
     *
     * @return the value of userrelationship.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getFeaturevector() {
        return featurevector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.featureVector
     *
     * @param featurevector the value for userrelationship.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setFeaturevector(String featurevector) {
        this.featurevector = featurevector == null ? null : featurevector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.likeCount
     *
     * @return the value of userrelationship.likeCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.likeCount
     *
     * @param likecount the value for userrelationship.likeCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.totalCount
     *
     * @return the value of userrelationship.totalCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.totalCount
     *
     * @param totalcount the value for userrelationship.totalCount
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrelationship.groupList
     *
     * @return the value of userrelationship.groupList
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getGrouplist() {
        return grouplist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrelationship.groupList
     *
     * @param grouplist the value for userrelationship.groupList
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGrouplist(String grouplist) {
        this.grouplist = grouplist == null ? null : grouplist.trim();
    }
}