package com.sdu.samus.model;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.nickname
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String schoolid5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.gender
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.intro
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String art;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String cartoon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.food
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String food;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.idol
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String idol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.game
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String game;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.movie
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String movie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.music
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String music;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String reading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sport
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String sport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.travel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String travel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private String featurevector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.avatar
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    private byte[] avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userId
     *
     * @return the value of userinfo.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userId
     *
     * @param userid the value for userinfo.userId
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.nickname
     *
     * @return the value of userinfo.nickname
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.nickname
     *
     * @param nickname the value for userinfo.nickname
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.schoolId5
     *
     * @return the value of userinfo.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getSchoolid5() {
        return schoolid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.schoolId5
     *
     * @param schoolid5 the value for userinfo.schoolId5
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setSchoolid5(String schoolid5) {
        this.schoolid5 = schoolid5 == null ? null : schoolid5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.gender
     *
     * @return the value of userinfo.gender
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.gender
     *
     * @param gender the value for userinfo.gender
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.intro
     *
     * @return the value of userinfo.intro
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.intro
     *
     * @param intro the value for userinfo.intro
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.art
     *
     * @return the value of userinfo.art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getArt() {
        return art;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.art
     *
     * @param art the value for userinfo.art
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setArt(String art) {
        this.art = art == null ? null : art.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.cartoon
     *
     * @return the value of userinfo.cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getCartoon() {
        return cartoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.cartoon
     *
     * @param cartoon the value for userinfo.cartoon
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setCartoon(String cartoon) {
        this.cartoon = cartoon == null ? null : cartoon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.food
     *
     * @return the value of userinfo.food
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getFood() {
        return food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.food
     *
     * @param food the value for userinfo.food
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setFood(String food) {
        this.food = food == null ? null : food.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.idol
     *
     * @return the value of userinfo.idol
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getIdol() {
        return idol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.idol
     *
     * @param idol the value for userinfo.idol
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setIdol(String idol) {
        this.idol = idol == null ? null : idol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.game
     *
     * @return the value of userinfo.game
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getGame() {
        return game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.game
     *
     * @param game the value for userinfo.game
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setGame(String game) {
        this.game = game == null ? null : game.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.movie
     *
     * @return the value of userinfo.movie
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getMovie() {
        return movie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.movie
     *
     * @param movie the value for userinfo.movie
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setMovie(String movie) {
        this.movie = movie == null ? null : movie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.music
     *
     * @return the value of userinfo.music
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getMusic() {
        return music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.music
     *
     * @param music the value for userinfo.music
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setMusic(String music) {
        this.music = music == null ? null : music.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.reading
     *
     * @return the value of userinfo.reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getReading() {
        return reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.reading
     *
     * @param reading the value for userinfo.reading
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setReading(String reading) {
        this.reading = reading == null ? null : reading.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sport
     *
     * @return the value of userinfo.sport
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sport
     *
     * @param sport the value for userinfo.sport
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setSport(String sport) {
        this.sport = sport == null ? null : sport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.travel
     *
     * @return the value of userinfo.travel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getTravel() {
        return travel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.travel
     *
     * @param travel the value for userinfo.travel
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setTravel(String travel) {
        this.travel = travel == null ? null : travel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.featureVector
     *
     * @return the value of userinfo.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public String getFeaturevector() {
        return featurevector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.featureVector
     *
     * @param featurevector the value for userinfo.featureVector
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setFeaturevector(String featurevector) {
        this.featurevector = featurevector == null ? null : featurevector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.avatar
     *
     * @return the value of userinfo.avatar
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public byte[] getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.avatar
     *
     * @param avatar the value for userinfo.avatar
     *
     * @mbg.generated Sun May 06 10:37:18 CST 2018
     */
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
}